In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install --upgrade pip wheel jedi # pacotes básicos

!pip install spacy --upgrade # spaCy
!python -m spacy download pt_core_news_lg # modelo de linguagem em português

!pip install emoji --upgrade # Emoji

!pip install pyspellchecker --upgrade # pyspellchecker

!pip install matplotlib --upgrade # matplotlib

Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (24.1.2)
Collecting pip
  Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (0.45.1)
Collecting jedi
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi) (0.8.4)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.0 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 24.7 MB/s eta 0:00:00
Installing collected packages: pip, jedi
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed jedi-0.19.2 pip-24.3.1
Requirement already satisfied: spacy in /usr/local/lib/python3.11/dist-packages (3.7.5)
Collecting spacy
  Downloading spacy-3.8.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.9)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.5.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.10.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.1.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.12.14)
Collecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Downloading spacy-3.8.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.6/30.6 MB 83.1 MB/s eta 0:00:00
Downloading thinc-8.3.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 89.7 MB/s eta 0:00:00
Downloading blis-1.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 97.8 MB/s eta 0:00:00
Installing collected packages: blis, thinc, spacy
  Attempting uninstall: blis
    Found existing installation: blis 0.7.11
    Uninstalling blis-0.7.11:
      Successfully uninstalled blis-0.7.11
  Attempting uninstall: thinc
    Found existing installation: thinc 8.2.5
    Uninstalling thinc-8.2.5:
      Successfully uninstalled thinc-8.2.5
  Attempting uninstall: spacy
    Found existing installation: spacy 3.7.5
    Uninstalling spacy-3.7.5:
      Successfully uninstalled spacy-3.7.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
en-core-web-sm 3.7.1 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.4 which is incompatible.
Successfully installed blis-1.2.0 spacy-3.8.4 thinc-8.3.4
Collecting pt-core-news-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_lg-3.8.0/pt_core_news_lg-3.8.0-py3-none-any.whl (568.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 568.2/568.2 MB 44.0 MB/s eta 0:00:00
Installing collected packages: pt-core-news-lg
Successfully installed pt-core-news-lg-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 10.7 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1
Collecting pyspellchecker
  Downloading pyspellchecker-0.8.2-py3-none-any.whl.metadata (9.4 kB)
Downloading pyspellchecker-0.8.2-py3-none-any.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 65.9 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.8.2
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [ ]:
MEU_DRIVE = "/content/drive/MyDrive/IC"

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel(MEU_DRIVE + '/Recursos/Amostras/Cópia de tweets-2022_10_10-query_bolsonaro.xlsx')

In [ ]:
df.head()

,Unnamed: 0,id,text,created_at,source,lang,conversation_id,like_count,retweet_count,quote_count,reply_count,type,referenced_tweet_id,mentions,hashtags,urls,author_id,media_keys\n
0,0,1579260419415638016,@elained78846426 @DamaresAlves Esse ficou até ...,2022-10-09 23:59:59,Twitter for Android,pt,1578521449156857856,0,0,0,0,replied_to,1578591135064535044,"970503822710894592, 1083774484123975680",NaN,NaN,1503910849999745024,\n
1,1,1579260417607864321,@marcogiotto @MariaAlima12 @SF_Moro Estou com ...,2022-10-09 23:59:59,Twitter for iPhone,pt,1578921089660375040,1,0,0,0,replied_to,1578921089660375040,"167243310, 1397709134913490948, 11130948552810...",NaN,NaN,1286674287533883395,\n
2,2,1579260414030147586,Bom. Vou comer uma pizza e tentar esquecer um ...,2022-10-09 23:59:58,Twitter for Android,pt,1579260414030147586,1,0,0,0,tweeted,NaN,NaN,NaN,NaN,177195567,\n
3,3,1579260413027368961,É o capitão do Povo que vai VENCER de novo!! D...,2022-10-09 23:59:58,Twitter for iPhone,pt,1579260413027368961,94,17,0,2,tweeted,NaN,NaN,NaN,https://t.co/vnV363iHFv,1256008487299145728,7_1579260377757523968\n
4,4,1579260409130860544,"é platão, parece que ainda tem gente que vive ...",2022-10-09 23:59:57,Twitter for iPhone,pt,1579260409130860544,4,0,0,0,tweeted,NaN,NaN,NaN,NaN,1022290166264815618,\n

In [ ]:
df.columns.values

array(['Unnamed: 0', 'id', 'text', 'created_at', 'source', 'lang',
       'conversation_id', 'like_count', 'retweet_count', 'quote_count',
       'reply_count', 'type', 'referenced_tweet_id', 'mentions',
       'hashtags', 'urls', 'author_id', 'media_keys\n'], dtype=object)

In [ ]:
df.lang.value_counts()

lang
pt    10000
Name: count, dtype: int64

In [ ]:
df.type.value_counts()

type
replied_to            6619
tweeted               2281
quoted                 976
quoted, replied_to     124
Name: count, dtype: int64

In [ ]:
df.info()

In [ ]:
import spacy
nlp = spacy.load('pt_core_news_lg')

entidades_nomeadas = {}
for tweet in df['text'][:100]:
    doc = nlp(tweet)
    for ent in doc.ents:
        if ent.label_ not in entidades_nomeadas:
            entidades_nomeadas[ent.label_] = set()
        entidades_nomeadas[ent.label_].add(ent.text)
for label, entidades in entidades_nomeadas.items():
    lista_entidades = sorted(entidades)
    print(f'{label}: {lista_entidades}')

PER: ['@BlogdoBG Pra', '@CorrupcaoMemes Ces', '@Vincius55916192 @costenaro_da', '@Zambelli2210', '@carlinhoscury', '@jojopeupeu @OliverStuenkel', '@oboltinho', '@patriota_ju', '@ricardostuckert Kkkkk', 'Aaaa\nPosso', 'Achei', 'América', 'André Janones', 'BOLSONARO', 'Bolsonaro', 'Bonner', 'Branco', 'Celso Rocha de Barros', 'Ciro', 'Collor', 'Cássio Nunes', 'Deus', 'Flordelis', 'Gleisi', 'Goleiro Bruno', 'Guilherme de Pádua', 'Jair', 'Jair Messias', 'Kim Jong-un', 'Leo', 'Leão', 'Loola', 'Lula', 'Lula da minha tl pfv', 'MC rick', 'Marielle', 'Mario Bittencourt', 'Moro', 'Márcia Tribufu', 'ROUBAR', 'Romário', 'Rui', 'Simone', 'Tarcísio Bolsonaro', 'Tereza Campello', 'Triste', 'aplomb', 'leo pericles', 'loola', 'lula', 'minerva', 'platão', 'rachadinha', 'sr Jair', 'td']
MISC: ['@Senador142RJ Deixa quieto Silveira', '@TSEjusbr?!', '@cacauandrade17 @77_frota', '@caiohenriiqueee @acalistaa', '@diegoca35697924 @MauricioAscani0 @DeniseGontijo', '@freu_rodrigues', '@leandroruschel Idiota útil!!', 'AQUI', 'Auxílio Brasil', 'BOLSONARO 22\nSDV BOLSONARISTAS!', 'BOLSONARO✌', 'BolsonaroPresidente22', 'Bozo', 'CACHORRINHO DO COISO', 'DESCONDENADO', 'E ANUNCIA APOIO', 'E TEM UM', 'Eleiçoes2022', 'Ex-ministro', 'Fake News', 'Filósofos', 'Gov', 'JANONES EU AUTORIZO', 'MILICIANO', 'Marcola', 'PRO', 'Pastores', 'R C I S I', 'TRABALHADOR', 'Thanos', 'VICE DE RUI COSTA NA BAHIA', 'VIVE', 'VotoNuloNao', 'YEEEEAH DUDE CONHECI', 'ZERO PESSOAS', 'bozo', 'https://t.co/NJESDTz3jP\nVídeo', 'https://t.co/PP2dhKXKmu', 'https://t.co/SWW8Vaz5Tf', 'ÍDOLO @patriota']
LOC: ['@AnnaCas52758367 @LorenzaAgostini', '@Exmarxistaa Penso', '@JoseMedeirosMT Andei', '@MariaAlima12', '@MateusKiller22', '@cirogomes @AnaPaulaMatosBA', '@gleisi', '@hgfernan', '@koepepe @andre_silva020 Voto', '@l_lb25 @igordsda', '@marciatiburi', '@ptbrasil', '@roger_saravy @ArianeSorrisoo Venezuela', '@xicosa', 'América', 'América do Rio', 'Atibaia', 'BRASIL', 'Bolsonaro', 'BolsonaroReeleito\n', 'Bonoro', 'Brasil', 'Brasileiro de DEUS HONESTO DECENTE PATRIOTA', 'Cara', 'Cuba', 'FORASTEIRO MENTIROSO', 'Gardenal', 'Ja', 'KKKKKkkk', 'Kkkkkk \n\n', 'MENINODOMEP', 'MG', 'Maçonaro', 'Minas', 'Moçambique', 'Médio', 'Nordestino', 'OcapitaoVaiVencerOladrao', 'Presídio Central de Porto Alegre', 'Queiroz', 'Rio São Francisco', 'Roraima', 'SIMPLES', 'Sp', 'São Paulo', 'Unk', 'Venezuela', 'bolsonaro', 'brasil', 'morro do papagaio']
ORG: ['@institutopapo10', '@rcbdsouza1 @MarietaPeixoto', 'Banco!', 'Bolsonaro', 'Bolsonaro p', 'CHEGA', 'Cheque', 'DEMOCRATAS', 'DIZ', 'FDP', 'ForaBolsonaro \n#BolsonaroNuncaMais #Bolsonaro_o_pior_presidente_do_Brasil', 'JN', 'Jair', 'PCC', 'PT', 'PT\n\nBolsonaro', 'Povo', 'UP', 'bolsonaro', 'din din', 'https://t.co/T04ilbHmA8', 'https://t.co/Z20aCXLkFy', 'max hj cpa', 'pt']

In [ ]:
from itertools import groupby
from string import punctuation

repeticoes_pontuacoes = {p: [] for p in {'?', '!'}}
for tweet in df['text'][:500]:
  for caractere, grupo in groupby(tweet):
    lista_grupo = list(grupo)
    if caractere in {'?', '!'} and len(lista_grupo) > 1:
      repeticoes_pontuacoes[caractere].append((tweet, len(lista_grupo)))
for pontuacao, repeticoes in repeticoes_pontuacoes.items():
  if repeticoes:
    print(f'Repetições de "{pontuacao}":')
    for tweet, count in repeticoes:
      print(f'"{pontuacao}" se repete {count} vezes no tweet: {tweet}')

Repetições de "!":
"!" se repete 2 vezes no tweet: É o capitão do Povo que vai VENCER de novo!! Dia 30 é 2️⃣2️⃣ https://t.co/vnV363iHFv
"!" se repete 3 vezes no tweet: @leandroruschel Idiota útil!!! Acordem brasileiros!!! Vc que paga uma coisa dessas!!!B22🇧🇷
"!" se repete 3 vezes no tweet: @leandroruschel Idiota útil!!! Acordem brasileiros!!! Vc que paga uma coisa dessas!!!B22🇧🇷
"!" se repete 3 vezes no tweet: @leandroruschel Idiota útil!!! Acordem brasileiros!!! Vc que paga uma coisa dessas!!!B22🇧🇷
"!" se repete 2 vezes no tweet: @Tita34723214 @palas_athenada @otempo @kalliloliveira_ Oi Patricia, eu não amo mito nenhum, amo apenas meus filhos e não vou nunca dizer a eles que votei em um ex presidiário. Beijo!!
"!" se repete 3 vezes no tweet: @emirsader Todos sabem as Fake News do gabinete do Ódio foram bem gastas e nesta guerra de narrativas o material contra Bolsonaro, sua família e seus aliados são enormes! Ou seja dá mto bem p/combater fake news c/verdades sobre o Minto! Mas @AndreJanonesAdv faz mto bem o chumbo trocado!!!
"!" se repete 3 vezes no tweet: @josedas67445341 @teixeiramatt Fala sério!!! Bolsonaro o cara que decreta sigilo de 100 anos para fugir de investigação! Sem investigação não há corrupção, não é mesmo!!! Agora é Lula
"!" se repete 3 vezes no tweet: @josedas67445341 @teixeiramatt Fala sério!!! Bolsonaro o cara que decreta sigilo de 100 anos para fugir de investigação! Sem investigação não há corrupção, não é mesmo!!! Agora é Lula
"!" se repete 3 vezes no tweet: Que é isso? Só agora, no 2o. Turno, é “contra”o ABORTO, só pra ganhar voto da gente que é contra esse tipo de homicídio? Pode isso Arnaldo?
Bolsonaro 22🇧🇷🇧🇷🇧🇷🇧🇷 é 100% transparente!!! https://t.co/2hAiMmxDce
"!" se repete 3 vezes no tweet: SENTA O DEDO SE DÓ
JÁ ESTÁ ACERTADO, O PRÓXIMO MINISTRO DA CASA CIVIL DE BOLSONARO SERÁ EDUARDO CUNHA!!! ISSO MESMO, EDUARDO CUNHA!!!
VIU ISSO,
@AndreJanonesAdv
  ???
"!" se repete 3 vezes no tweet: SENTA O DEDO SE DÓ
JÁ ESTÁ ACERTADO, O PRÓXIMO MINISTRO DA CASA CIVIL DE BOLSONARO SERÁ EDUARDO CUNHA!!! ISSO MESMO, EDUARDO CUNHA!!!
VIU ISSO,
@AndreJanonesAdv
  ???
"!" se repete 4 vezes no tweet: @liberal22_rs @thunder_270380 Foi o Jair!!!!
"!" se repete 3 vezes no tweet: @jandira_feghali @ricardostuckert Quanto custa na sua cidade o litro da gasolina, do etanol, do leite, da cesta básica... abaixou pós pandemia!!! Então, foi o Presidente que conseguiu essas baixas de preços e não vai ser o 'L'adrão que vai te dar picanha e, sim, é o seu trabalho garantido pelo Bolsonaro e Guedes!
"!" se repete 3 vezes no tweet: @Miltonneves @terceirotempo Quanto custa na sua cidade o litro da gasolina, do etanol, do leite, da cesta básica... abaixou pós pandemia!!! Então, foi o Presidente que conseguiu essas baixas de preços e não vai ser o 'L'adrão que vai te dar picanha e, sim, é o seu trabalho garantido pelo Bolsonaro e Guedes!
"!" se repete 2 vezes no tweet: 🗣 Moro não apoiou nem vai apoiar Bolsonaro.
Moro não se declarou a favor de ninguém,ele só disse q o PT é uma desgraça ainda maior.
Qd o petista Algusto Aras foi chamado à PGR  p/ destruir a Lava-Jato, Moro percebeu q tipo de vagabundo era o chefe da noção.
– Um Patife.,!! ... https://t.co/EB4usnMbuR
"!" se repete 3 vezes no tweet: Quem enaltece Fernando Collor???? Bolsonaro e seus bolsonions… brasileiro tem que ser estudado mesmo. Tarcísio elogia um cara que destruiu muita gente. Imagino como será a vida dos paulistas… meu voto não teve e nem terá!!! https://t.co/ul2g9F7afk
"!" se repete 2 vezes no tweet: Não é Danone é leite condensado, talkey?!
VOTA VOTA E CONFIRMA: 22 É BOLSONARO!! https://t.co/yW2hPUiPTm
"!" se repete 3 vezes no tweet: @lulaverso Quanto custa na sua cidade o litro da gasolina, do etanol, do leite, da cesta básica... abaixou pós pandemia!!! Então, foi o Presidente que conseguiu essas baixas de preços e não vai ser o 'L'adrão que vai te dar picanha e, sim, é o seu trabalho garantido pelo Bolsonaro e Guedes!
"!" se repete 3 vezes no tweet: @scarnavalesco @LulaOficial 🎶Favela, pega a visão, não tem futuro sem partilha, nem Messias de arma na mão!!!🎶💚💗💚💗
"!" se repete 3 vezes no tweet: @cabogilberto Quanto custa na sua cidade o litro da gasolina, do etanol, do leite, da cesta básica... abaixou pós pandemia!!! Então, foi o Presidente que conseguiu essas baixas de preços e não vai ser o 'L'adrão que vai te dar picanha e, sim, é o seu trabalho garantido pelo Bolsonaro e Guedes!
"!" se repete 3 vezes no tweet: @Rconstantino NÃO FALE ASSIM DO MITO!!! MAIS RESPEITO COM NOSSO PRESIDENTE!!! ÍNDIO COM LEITE CONDENSADO DEVE SER GOSTOSO, E DAÍ????
"!" se repete 3 vezes no tweet: @Rconstantino NÃO FALE ASSIM DO MITO!!! MAIS RESPEITO COM NOSSO PRESIDENTE!!! ÍNDIO COM LEITE CONDENSADO DEVE SER GOSTOSO, E DAÍ????
"!" se repete 3 vezes no tweet: Não entendo como uma pessoa LGBT prefere apoiar um homofóbico  como bolsonaro!!! Será que @EduardoLeite_ não vê que ele é bem tratado por que faz o papel de homossexual bem comportado que a Faria Lima suporta???? É quando não servir mais??? https://t.co/gEC8oAUaYD
"!" se repete 2 vezes no tweet: @Miltonneves Bolsonaro não é alternativa, é a única opção para salvar o Brasil!! https://t.co/29OikvEzvH
"!" se repete 2 vezes no tweet: @andrevaladao VC LEMBRA MUITO BEM VIU!! APOIA O SEU GENOCIDA PQ TEM INTERESSES PRÓPRIOS. VCS FALSOS CRISTÃOS SÓ PENSAM NO PRÓPRIO UMBIGO
"!" se repete 2 vezes no tweet: @coloradoadriano @dale10 Nessa foto podemos ver um ídolo, um mito!! E ao lado o D’alessandro
"!" se repete 2 vezes no tweet: O @TSEjusbr @alexandre ACORDA!! Tá de sacanagem? Desde 2018 estamos denunciando as MENTIRAS do canibal maçonaro e vcs fazem absolutamente nada!! Vcs são defensores da DEMOCRACIA ou não sao? Chega! Somos democratas somos #LulaPresidente13 oi @CIJ_ICJ https://t.co/kfTiwN3ALU
"!" se repete 2 vezes no tweet: O @TSEjusbr @alexandre ACORDA!! Tá de sacanagem? Desde 2018 estamos denunciando as MENTIRAS do canibal maçonaro e vcs fazem absolutamente nada!! Vcs são defensores da DEMOCRACIA ou não sao? Chega! Somos democratas somos #LulaPresidente13 oi @CIJ_ICJ https://t.co/kfTiwN3ALU
"!" se repete 3 vezes no tweet: Os eventos do Bolsonaro aí nesse mesmo lugar sem a presença dele junta muito mais gente kkkkkkk Bolsonaro ganhou em BH e foi de lavada!!! https://t.co/u8f97rDIuW
"!" se repete 3 vezes no tweet: @NonaConta_ Scho que isso é  fake! Vamos nos concentrar em atrair votos p Bolsonaro!!!
"!" se repete 3 vezes no tweet: @arthurpicoli Quanto custa na sua cidade o litro da gasolina, do etanol, do leite, da cesta básica... abaixou pós pandemia!!! Então, foi o Presidente que conseguiu essas baixas de preços e não vai ser o 'L'adrão que vai te dar picanha e, sim, é o seu trabalho garantido pelo Bolsonaro e Guedes!
"!" se repete 3 vezes no tweet: @GuilhermeBoulos Tudo por culpa desse negacionista de merda que é contra a educação sexual nas escolas, onde isso se trata de saúde pública, além de dizer que o governo não investiriam mais nos coquetéis e remédios para a prevenção da doença. Esse Bozo é um maluco!!! Dia 30 é 13 na urna!!!🦑🚩🌟
"!" se repete 3 vezes no tweet: @GuilhermeBoulos Tudo por culpa desse negacionista de merda que é contra a educação sexual nas escolas, onde isso se trata de saúde pública, além de dizer que o governo não investiriam mais nos coquetéis e remédios para a prevenção da doença. Esse Bozo é um maluco!!! Dia 30 é 13 na urna!!!🦑🚩🌟
Repetições de "?":
"?" se repete 3 vezes no tweet: SENTA O DEDO SE DÓ
JÁ ESTÁ ACERTADO, O PRÓXIMO MINISTRO DA CASA CIVIL DE BOLSONARO SERÁ EDUARDO CUNHA!!! ISSO MESMO, EDUARDO CUNHA!!!
VIU ISSO,
@AndreJanonesAdv
  ???
"?" se repete 4 vezes no tweet: Quem enaltece Fernando Collor???? Bolsonaro e seus bolsonions… brasileiro tem que ser estudado mesmo. Tarcísio elogia um cara que destruiu muita gente. Imagino como será a vida dos paulistas… meu voto não teve e nem terá!!! https://t.co/ul2g9F7afk
"?" se repete 2 vezes no tweet: E alguém achou mesmo que ele ia apoiar Bolsonaro?? https://t.co/Lz2jv4sGqE
"?" se repete 4 vezes no tweet: @Rconstantino NÃO FALE ASSIM DO MITO!!! MAIS RESPEITO COM NOSSO PRESIDENTE!!! ÍNDIO COM LEITE CONDENSADO DEVE SER GOSTOSO, E DAÍ????
"?" se repete 4 vezes no tweet: Não entendo como uma pessoa LGBT prefere apoiar um homofóbico  como bolsonaro!!! Será que @EduardoLeite_ não vê que ele é bem tratado por que faz o papel de homossexual bem comportado que a Faria Lima suporta???? É quando não servir mais??? https://t.co/gEC8oAUaYD
"?" se repete 3 vezes no tweet: Não entendo como uma pessoa LGBT prefere apoiar um homofóbico  como bolsonaro!!! Será que @EduardoLeite_ não vê que ele é bem tratado por que faz o papel de homossexual bem comportado que a Faria Lima suporta???? É quando não servir mais??? https://t.co/gEC8oAUaYD
"?" se repete 3 vezes no tweet: @filipesabara Uma ameaça??? O próximo presidente depois de Bolsonaro vai ser o Zema , só de raiva agora.
"?" se repete 2 vezes no tweet: Essa gente que usa o discurso do aborto como argumento pra atacar o pt acha que so pq eles são contra a legalização q ele vai deixar de existir ?? Pq eu sou contra o Bolsonaro e infelizmente ele existe ainda

In [ ]:
# Função para corrigir ortografia
def corrigir_tweet(tweet):
    pontuacoes = string.punctuation + '’‘“”ºª°…—–«»¯´'
    palavras_corrigidas = []
    cache_corrigidas = {}
    for word in tweet.split():
        # Remove pontuação e normaliza a palavra
        word_normalizada = word.translate(str.maketrans('', '', pontuacoes)).lower()
        # Verifica se a palavra já foi corrigida antes
        if word_normalizada in cache_corrigidas:
            palavra_corrigida = cache_corrigidas[word_normalizada]
        else:
            # Corrige a palavra e armazena no cache
            palavra_corrigida = spellchecker.correction(word_normalizada)
            cache_corrigidas[word_normalizada] = palavra_corrigida
        # Adiciona a palavra corrigida ou original à lista
        if palavra_corrigida:
            palavras_corrigidas.append(palavra_corrigida)
        else:
            palavras_corrigidas.append(word)
    return ' '.join(palavras_corrigidas)

### Térmos técnicos

In [ ]:
# # UDlexPT - léxico geral
# import sys
# sys.path.append('/content/drive/MyDrive/IC/Recursos/PortiLexicon-UD')
# from UDlexPT import UDlexPT
# UDlexPT = UDlexPT()

# # pontuações (que serão removidas dos tweets)
# import string
# pontuacoes = string.punctuation + '’‘“”ºª°…—–«»¯´'

# # Enelvo - normalizador
# sys.path.append('/content/drive/MyDrive/IC/Recursos/')
# from enelvo import normaliser
# norm = normaliser.Normaliser(fc_list='/content/drive/MyDrive/IC/Recursos/force-list.txt',ig_list='/content/drive/MyDrive/IC/Recursos/ignore-list.txt')

# # spaCy - biblioteca para PLN
# import spacy
# nlp = spacy.load('pt_core_news_lg')  # carregando o modelo em português

# # pyspellchecker - corretor ortográfico
# from spellchecker import SpellChecker
# spellchecker = SpellChecker(language='pt')  # inicializando o corretor para o idioma português


# def eh_termo_tecnico(word, entidades_per_gpe, pos):
#     return (not UDlexPT.exists(word) and  # a palavra não está no léxico geral
#             word not in entidades_per_gpe and  # não é pessoa ou local
#             pos not in {'ADP', 'SCONJ', 'PRON', 'DET'} and  # não é preposição, conjunção subordinativa, pronome ou determinante
#             word.isalnum() and  # é alfanumérica
#             not word.isnumeric() and  # não é numérica
#             len(word) > 1)  # tem mais de um caractere


# termos_tecnicos = set()
# df = pd.read_excel(MEU_DRIVE + '/Recursos/Amostras/Cópia de tweets-2022_10_10-query_bolsonaro.xlsx')

# for tweet in df['text'][:1000]:
#     norm_sentence = norm.normalise(tweet)  # normalizando o tweet
#     doc = nlp(norm_sentence)
#     entidades_per_gpe = {ent.text for ent in doc.ents if ent.label_ in {'PER', 'GPE', 'LOC'}}
#     for token in doc:
#         word = token.text.translate(str.maketrans('', '', pontuacoes))  # removendo pontuações do token
#         if not UDlexPT.exists(word):
#             correcao = spellchecker.correction(word)
#             if correcao:
#                 word = correcao  # corrigindo a ortografia da palavra
#         # se a palavra for um termo técnico, adiciona ao conjunto
#         if eh_termo_tecnico(word, entidades_per_gpe, token.pos_):
#             termos_tecnicos.add(word)
# termos_tecnicos = sorted(termos_tecnicos)

# # Termos técnicos agrupados por letra inicial
# letra_atual = ''
# termos_para_letra = []
# for termo in termos_tecnicos:
#     letra_inicial = termo[0].upper()
#     if letra_inicial != letra_atual:
#         if termos_para_letra:
#             print(f'"{letra_atual}": {termos_para_letra}')
#         letra_atual = letra_inicial
#         termos_para_letra = [termo]
#     else:
#         termos_para_letra.append(termo)
# if termos_para_letra:
#     print(f'"{letra_atual}": {termos_para_letra}')

In [ ]:
# import spacy
# import emoji
# from itertools import groupby
# import string
# from spellchecker import SpellChecker
# import re
# import sys
# sys.path.append('/content/drive/MyDrive/IC/Recursos/PortiLexicon-UD')
# from UDlexPT import UDlexPT
# sys.path.append('/content/drive/MyDrive/IC/Recursos/')
# from enelvo import normaliser

# norm = normaliser.Normaliser(fc_list='/content/drive/MyDrive/IC/Recursos/force-list.txt',ig_list='/content/drive/MyDrive/IC/Recursos/ignore-list.txt')

# # Carregar o modelo spaCy para o português
# nlp = spacy.load('pt_core_news_lg')

# # Inicializar o corretor ortográfico
# spellchecker = SpellChecker(language='pt')

# # Inicializar o UDlexPT
# UDlexPT = UDlexPT()

# # Função para identificar autoridades
# def identificar_autoridades(tweet):
#     doc = nlp(tweet)
#     autoridades = [ent.text for ent in doc.ents if ent.label_ in {'PER', 'ORG'}]
#     return autoridades

# # Função para identificar emojis
# def identificar_emojis(tweet):
#     return [caractere for caractere in tweet if emoji.is_emoji(caractere)]

# # Função para identificar caixa alta
# def identificar_caixa_alta(tweet):
#     ignorar_inicial = {'A', 'O', 'É', 'E'}
#     doc = nlp(tweet)
#     caixa_alta = []
#     for i, token in enumerate(doc):
#         # Ignora palavras no início da frase que estão na lista ignorar_inicial
#         if i == 0 and token.text in ignorar_inicial:
#             continue
#         # Verifica se a palavra está em caixa alta e não é um caso de início de frase
#         if token.text.isupper():
#             caixa_alta.append(token.text)
#     return caixa_alta


# # Função para identificar hashtags
# def identificar_hashtags(tweet):
#     hashtags = re.findall(r'#\S+', tweet)
#     return hashtags

# # Função para identificar repetição de sinais de pontuação
# def identificar_repeticoes_pontuacao(tweet):
#     repeticoes = {}
#     for caractere, grupo in groupby(tweet):
#         if caractere in {'?', '!'}:
#             lista_grupo = list(grupo)
#             if len(lista_grupo) > 1:
#                 repeticoes[caractere] = len(lista_grupo)
#     return repeticoes

# # Função para corrigir ortografia
# def corrigir_tweet(tweet):
#     pontuacoes = string.punctuation + '’‘“”ºª°…—–«»¯´'
#     palavras_corrigidas = []
#     cache_corrigidas = {}
#     for word in tweet.split():
#         # Remove pontuação e normaliza a palavra
#         word_normalizada = word.translate(str.maketrans('', '', pontuacoes)).lower()
#         # Verifica se a palavra já foi corrigida antes
#         if word_normalizada in cache_corrigidas:
#             palavra_corrigida = cache_corrigidas[word_normalizada]
#         else:
#             # Corrige a palavra e armazena no cache
#             palavra_corrigida = spellchecker.correction(word_normalizada)
#             cache_corrigidas[word_normalizada] = palavra_corrigida
#         # Adiciona a palavra corrigida ou original à lista
#         if palavra_corrigida:
#             palavras_corrigidas.append(palavra_corrigida)
#         else:
#             palavras_corrigidas.append(word)
#     return ' '.join(palavras_corrigidas)


# def identificar_termos_tecnicos(tweet):
#     # Função auxiliar para verificar se uma palavra é um termo técnico
#     def eh_termo_tecnico(word_corrigida, entidades_per_gpe, pos):
#         return (not UDlexPT.exists(word_corrigida) and
#                 word_corrigida not in entidades_per_gpe and
#                 pos not in {'ADP', 'SCONJ', 'PRON'} and
#                 word_corrigida.isalnum())

#     # Configurações iniciais
#     pontuacoes = string.punctuation + '’‘“”ºª°…—–«»¯´'
#     termos_tecnicos = set()
#     norm_sentence = norm.normalise(tweet)  # normalizando o tweet
#     doc = nlp(norm_sentence)
#     entidades_per_gpe = {ent.text for ent in doc.ents if ent.label_ in {'PER', 'GPE'}}
#     for token in doc:
#         word = token.text.translate(str.maketrans('', '', pontuacoes))
#         word_corrigida = spellchecker.correction(word)
#         if word_corrigida and eh_termo_tecnico(word_corrigida, entidades_per_gpe, token.pos_):
#             termos_tecnicos.add(word_corrigida)
#     return sorted(termos_tecnicos) if termos_tecnicos else None

# # Função para identificar verbos e pronomes na primeira pessoa
# def identificar_relatos_pessoais(tweet):
#     norm_sentence = norm.normalise(tweet)  # normalizando o tweet
#     doc = nlp(norm_sentence)
#     verbos = []
#     pronomes = []
#     for token in doc:
#         if token.morph.get('Person') == ['1']:
#             if token.pos_ == 'VERB':
#                 verbos.append(token.text)
#             elif token.pos_ == 'PRON':
#                 pronomes.append(token.text)
#     return verbos, pronomes

In [ ]:
# def processar_tweet(tweet):
#     print(f'\nTweet: {tweet}')

#     autoridades = identificar_autoridades(tweet)
#     if autoridades:
#         print(f'Autoridades: {autoridades}')

#     emojis = identificar_emojis(tweet)
#     if emojis:
#         print(f'Emojis encontrados: {emojis}')

#     caixa_alta = identificar_caixa_alta(tweet)
#     if caixa_alta:
#         print(f'Palavras em caixa alta: {caixa_alta}')

#     hashtags = identificar_hashtags(tweet)
#     if hashtags:
#         print(f'Hashtags: {hashtags}')

#     repeticoes = identificar_repeticoes_pontuacao(tweet)
#     if repeticoes:
#         for caractere, count in repeticoes.items():
#             print(f'"{caractere}" se repete {count} vezes')

#     termos_tecnicos = identificar_termos_tecnicos(tweet)
#     if termos_tecnicos:
#         print(f'Termos técnicos: {termos_tecnicos}')

#     verbos, pronomes = identificar_relatos_pessoais(tweet)
#     if verbos:
#         print(f'Verbos na 1ª pessoa: {verbos}')
#     if pronomes:
#         print(f'Pronomes na 1ª pessoa: {pronomes}')

# # Processar cada tweet
# for tweet in df['text'][:100]:
#     processar_tweet(tweet)

## Melhorando a identificação de termos técnicos

In [ ]:
df_nomes_fem = pd.read_csv(MEU_DRIVE + '/Recursos/ibge-fem-10000.csv')

In [ ]:
df_nomes_fem = df_nomes_fem.filter(items=['nome'])

In [ ]:
df_nomes_masc = pd.read_csv(MEU_DRIVE + '/Recursos/ibge-mas-10000.csv')

In [ ]:
df_nomes_masc = df_nomes_masc.filter(items=['nome'])

In [ ]:
df_nomes_fem['nome'] = df_nomes_fem['nome'].str.lower()

In [ ]:
df_nomes_masc['nome'] = df_nomes_masc['nome'].str.lower()

In [ ]:
df_paises = pd.read_json(MEU_DRIVE + '/Recursos/paises-array.json')

In [ ]:
df_paises = df_paises.filter(items=['nome'])

In [ ]:
df_estados = pd.read_csv(MEU_DRIVE + '/Recursos/municipios.csv')

In [ ]:
df_estados = df_estados.filter(items=['nome'])

In [ ]:
df_municipios = pd.read_csv(MEU_DRIVE + '/Recursos/municipios.csv')

In [ ]:
df_municipios = df_municipios.filter(items=['nome'])

In [ ]:
import re

# UDlexPT - léxico geral
import sys
sys.path.append('/content/drive/MyDrive/IC/Recursos/PortiLexicon-UD')
from UDlexPT import UDlexPT
UDlexPT = UDlexPT()

# pontuações (que serão removidas dos tweets)
import string
pontuacoes = string.punctuation + '’‘“”ºª°…—–«»¯´'

# Enelvo - normalizador
sys.path.append('/content/drive/MyDrive/IC/Recursos/')
from enelvo import normaliser
norm = normaliser.Normaliser(fc_list='/content/drive/MyDrive/IC/Recursos/force-list.txt',ig_list='/content/drive/MyDrive/IC/Recursos/ignore-list.txt')

# spaCy - biblioteca para PLN
import spacy
nlp = spacy.load('pt_core_news_lg')  # carregando o modelo em português

# pyspellchecker - corretor ortográfico
from spellchecker import SpellChecker
spellchecker = SpellChecker(language='pt')  # inicializando o corretor para o idioma português

import unicodedata

def remover_acentos(palavra):
    return ''.join(c for c in unicodedata.normalize('NFD', palavra) if unicodedata.category(c) != 'Mn')

def eh_risada(word):
    return bool(re.fullmatch(r'(ha)+|k+', word, re.IGNORECASE))

def eh_link(word):
    return bool(re.match(r'(http|www)\.|\.com|\.br|\.org|@\w+', word))

def corrigir_hifen_palavras(palavra):
    if re.match(r'^(ex|vice)[a-záàâãéèêíïóôõöúçñ]+$', palavra, re.IGNORECASE):
        return re.sub(r'^(ex|vice)', r'\1-', palavra)
    if re.match(r'^(pós|pré|pró)[a-záàâãéèêíïóôõöúçñ]+$', palavra, re.IGNORECASE):
        return re.sub(r'^(pós|pré|pró)', r'\1-', palavra)
    return palavra


def eh_termo_tecnico(word, entidades_per_gpe, pos):
    return (not UDlexPT.exists(word) and  # a palavra não está no léxico geral
            word not in entidades_per_gpe and  # não é pessoa ou local
            word not in df_paises['nome'].values and
            word not in df_estados['nome'].values and
            word not in df_municipios['nome'].values and
            remover_acentos(word.lower()) not in df_nomes_fem['nome'].values and  # não é nome feminino
            remover_acentos(word.lower()) not in df_nomes_masc['nome'].values and  # não é nome masculino
            not eh_risada(word) and
            not eh_link(word) and
            pos not in {'ADP', 'SCONJ', 'PRON', 'DET'} and  # não é preposição, conjunção subordinativa, pronome ou determinante
            word.isalnum() and  # é alfanumérica
            not word.isnumeric() and  # não é numérica
            len(word) > 1)  # tem mais de um caractere


termos_tecnicos = set()
df = pd.read_excel(MEU_DRIVE + '/Recursos/Amostras/Cópia de tweets-2022_10_10-query_bolsonaro.xlsx')

for tweet in df['text'][2000:]:
    norm_sentence = norm.normalise(tweet)  # normalizando o tweet
    doc = nlp(norm_sentence)
    entidades_per_gpe = {ent.text for ent in doc.ents if ent.label_ in {'PER', 'GPE', 'LOC'}}
    for token in doc:
        word = token.text.translate(str.maketrans('', '', pontuacoes))  # removendo pontuações do token
        word = corrigir_hifen_palavras(word)
        if not UDlexPT.exists(word):
            correcao = spellchecker.correction(word)
            if correcao:
                word = correcao  # corrigindo a ortografia da palavra
        # se a palavra for um termo técnico, adiciona ao conjunto
        if eh_termo_tecnico(word, entidades_per_gpe, token.pos_):
            termos_tecnicos.add(word)
termos_tecnicos = sorted(termos_tecnicos)

# Termos técnicos agrupados por letra inicial
letra_atual = ''
termos_para_letra = []
for termo in termos_tecnicos:
    letra_inicial = termo[0].upper()
    if letra_inicial != letra_atual:
        if termos_para_letra:
            print(f'"{letra_atual}": {termos_para_letra}')
        letra_atual = letra_inicial
        termos_para_letra = [termo]
    else:
        termos_para_letra.append(termo)
if termos_para_letra:
    print(f'"{letra_atual}": {termos_para_letra}')

UDlexPT read with 862325 distinct words and 1226343 entries
tag   & total  & amb    & non-amb \\ \hline
ADJ   & 124332 &  79165 &  45167 & 124453 \\ \hline
ADP   &     38 &     26 &     12 &     38 \\ \hline
ADV   &   4938 &   1838 &   3100 &   4944 \\ \hline
AUX   &    332 &    277 &     55 &    435 \\ \hline
CCONJ &     25 &     17 &      8 &     25 \\ \hline
DET   &    109 &    105 &      4 &    117 \\ \hline
INTJ  &     41 &     12 &     29 &     41 \\ \hline
NOUN  &  75154 &  26807 &  48347 &  75377 \\ \hline
NUM   &     53 &     42 &     11 &     54 \\ \hline
PRON  &    157 &    123 &     34 &    180 \\ \hline
SCONJ &     14 &     13 &      1 &     14 \\ \hline
VERB  & 746783 &  65672 & 681111 & 1020665 \\ \hline
total & 862325 &  84446 & 777879 & 1226343 \\ \hline

ERROR:enelvo.normaliser:Failed to normalise word "crimescontra"!
ERROR:enelvo.normaliser:Failed to normalise word "vainreduzir"!
ERROR:enelvo.normaliser:Failed to normalise word "quendefende"!
ERROR:enelvo.normaliser:Failed to normalise word "shidajsjd"!
ERROR:enelvo.normaliser:Failed to normalise word "auuaisaisi"!
ERROR:enelvo.normaliser:Failed to normalise word "kakakakakakaak"!
ERROR:enelvo.normaliser:Failed to normalise word "khadaffi"!
ERROR:enelvo.normaliser:Failed to normalise word "coranavoucher"!
ERROR:enelvo.normaliser:Failed to normalise word "weitraudt"!
ERROR:enelvo.normaliser:Failed to normalise word "homeschooling"!
ERROR:enelvo.normaliser:Failed to normalise word "ahahahahhahaha"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsoinvest"!
ERROR:enelvo.normaliser:Failed to normalise word "pornoafetivo"!
ERROR:enelvo.normaliser:Failed to normalise word "reginaduarte"!
ERROR:enelvo.normaliser:Failed to normalise word "megaempresário"!
ERROR:enelvo.normaliser:Failed to normalise word "impeachtimado"!
ERROR:enelvo.normaliser:Failed to normalise word "onlyfans"!
ERROR:enelvo.normaliser:Failed to normalise word "nooossaaa"!
ERROR:enelvo.normaliser:Failed to normalise word "ddsjkkkifo"!
ERROR:enelvo.normaliser:Failed to normalise word "truthsocial"!
ERROR:enelvo.normaliser:Failed to normalise word "truthsocial"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsofascistas"!
ERROR:enelvo.normaliser:Failed to normalise word "truthsocial"!
ERROR:enelvo.normaliser:Failed to normalise word "luladrãonistas"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsomions"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsominium"!
ERROR:enelvo.normaliser:Failed to normalise word "disgranhenta"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsominon"!
ERROR:enelvo.normaliser:Failed to normalise word "coronavírus"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsiminion"!
ERROR:enelvo.normaliser:Failed to normalise word "bolsominons"!
ERROR:enelvo.normaliser:Failed to normalise word "tenryuubito"!